// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOo-uCaFPT7eMYRHiSgfEHKzya-U20y10',
    appId: '1:636409261888:web:1e654de988e1412f0e94a5',
    messagingSenderId: '636409261888',
    projectId: 'e-commerce-lwn-c80a3',
    authDomain: 'e-commerce-lwn-c80a3.firebaseapp.com',
    storageBucket: 'e-commerce-lwn-c80a3.firebasestorage.app',
    measurementId: 'G-ZNEM1K77V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP7CJOXthvsKknOd6POROMocAQUGyih04',
    appId: '1:636409261888:android:e107b8200eb63d9f0e94a5',
    messagingSenderId: '636409261888',
    projectId: 'e-commerce-lwn-c80a3',
    storageBucket: 'e-commerce-lwn-c80a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBLryLICiln4wiZ7Gq132b9Q0B27U9Fk',
    appId: '1:636409261888:ios:0f9fb4ab57fa3f970e94a5',
    messagingSenderId: '636409261888',
    projectId: 'e-commerce-lwn-c80a3',
    storageBucket: 'e-commerce-lwn-c80a3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBLryLICiln4wiZ7Gq132b9Q0B27U9Fk',
    appId: '1:636409261888:ios:0f9fb4ab57fa3f970e94a5',
    messagingSenderId: '636409261888',
    projectId: 'e-commerce-lwn-c80a3',
    storageBucket: 'e-commerce-lwn-c80a3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOo-uCaFPT7eMYRHiSgfEHKzya-U20y10',
    appId: '1:636409261888:web:45b16762e0de2e3e0e94a5',
    messagingSenderId: '636409261888',
    projectId: 'e-commerce-lwn-c80a3',
    authDomain: 'e-commerce-lwn-c80a3.firebaseapp.com',
    storageBucket: 'e-commerce-lwn-c80a3.firebasestorage.app',
    measurementId: 'G-8F9093R5YV',
  );
}
